### ISSUE TITLE
Question: Does HuntStats Lifetrack?

### ISSUE THREAD

**Issue by Dultus** [Zaxiure/HuntStats#31]
Good morning,
the title says it all. I'm wondering if the changes are made live so I could perhaps use information for events on my PC. E.g. displaying it on my display.

Thank you!

**Comment by Zaxiure** [comment]
The app does indeed live update whenever a new match is registered.

**Comment by Dultus** [comment]
Thank you very much for the fast response! That's very good to know! 😄
